[build-system]
requires = ["setuptools", "wheel", "Cython@git+https://github.com/cython/cython.git@c25c87d71107e634162302f7f61a119eff539a48", "numpy"]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
src_paths = ["."]
line_length = 120
